[package]
name = "new_minesweeper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
grid = "0.6.0"
itertools = "0.10.2"
tuple = "0.3.5"
